name: SpawnCommand
version: 1.1
api: [3.0.0]
author: WortTuner
main: SpawnCommand\Main

commands:
  spawn:
    description: "Teleport to spawn"
    usage: "/spawn"
    permission: "spawncommand.command.spawn"
  setspawn:
    description: "Set server spawn"
    usage: "/setspawn"

permissions:
  spawn:
    default: true
    description: "Allows player to go to spawn point"
  setspawn:
    default: op
    description: "Allows player to set the server spawn."

